dotnet-project-file-analyzers/dotnet-project-file-analyzers.github.io

- README.md
- rules/Proj1100.md
See: https://www.reddit.com/r/dotnet/comments/15ljdcc/does_moq_in_its_latest_version_extract_and_send/
> Proj1100: Avoid using Moq

- README.md
- rules/Proj1200.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/88
> Proj1200: Exclude private assets as project file dependency

- rules/Proj0004.md
To align with https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/94.
> Adjust documentation for Proj0004

- README.md
- rules/Proj0020.md
Analyzer PR: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/85
> Proj0020 Item group should only contain nodes of a single type

- README.md
- rules/Proj0600.md
Implementation PR: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/106
> Add documentation for Proj0600

- README.md
- rules/Proj0240.md
- rules/Proj0241.md
Implementation: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/109
> New rules: Proj0240 and Proj0241 - Enable package validation

- README.md
- rules/Proj0242.md
See: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/125
> Add documentation for Proj0242

- README.md
- rules/configuration.md
Documentation update required for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/124.
> Add documentation about config and suppression

- README.md
- rules/Proj0024.md
Implementation: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/132
> Proj0024: Order package versions alphabetically

- README.md
- rules/Proj1700.md
Related to: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/135
> Documentation for Proj1700; Indent XML

- rules/Proj1200.md
- rules/configuration.md
> Fix typo's

- README.md
- rules/Proj2100.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/141
> Proj2100: Indent RESX

- README.md
- rules/Proj0007.md
- rules/Proj0008.md
- rules/Proj0009.md
- rules/Proj0010.md
- rules/Proj0011.md
- rules/Proj0200.md
- rules/Proj0201.md
- rules/Proj0202.md
- rules/Proj0203.md
- rules/Proj0204.md
- rules/Proj0205.md
- rules/Proj0206.md
- rules/Proj0207.md
- rules/Proj0208.md
- rules/Proj0209.md
- rules/Proj0210.md
- rules/Proj0211.md
- rules/Proj0212.md
- rules/Proj0213.md
- rules/Proj0214.md
- rules/Proj0240.md
- rules/Proj0241.md
- rules/Proj0242.md
- rules/Proj0400.md
- rules/Proj0600.md
- rules/Proj0800.md
- rules/Proj0801.md
Documentation for: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/145
> Proj0800 & Proj081: CPM

- README.md
- rules/Proj0803.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/151
> Proj0803: Use VersionOverride only with Central Package Management enabled

- README.md
- rules/Proj0806.md
Documentation by https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/155
> Proj0806: VersionOverride should change the version

- rules/Proj0800.md
> Add link to CentralisedPackageConverter

- README.md
- rules/Proj1701.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/157
> Proj1701: Use <![CDATA[ for large texts

- README.md
- rules/Proj1702.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/162
> Proj1702: Omit XML declarations

- README.md
- rules/Proj0450.md
- rules/Proj0451.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/177
> Proj0450 & Proj0451: Test project shouldn't publish nor package

- README.md
- rules/Proj0025.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/179
> Proj0025: Migrate from ruleset file to .editorconfig file

- general/nuget-packages.md
- rules/Proj0200.md
- rules/Proj0201.md
- rules/Proj0202.md
- rules/Proj0203.md
- rules/Proj0204.md
- rules/Proj0205.md
- rules/Proj0206.md
- rules/Proj0207.md
- rules/Proj0208.md
- rules/Proj0209.md
- rules/Proj0210.md
- rules/Proj0211.md
- rules/Proj0212.md
- rules/Proj0213.md
- rules/Proj0214.md
Useful overview on all NuGet package related rules. See also: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/issues/26
> Documentation of NuGet package rules

- README.md
- general/nuget-packages.md
- rules/Proj0215.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/180
> Proj0215: Provide a compliant NuGet package icon

- README.md
- rules/Proj0026.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/182
> Proj0026: Remove IncludeAssets when redundant

- README.md
- rules/Proj0027.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/issues/98
> Proj0027: Update <TargetFrameworks> with <TargetFrameworks>

- README.md
- rules/Proj0028.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/186
> Proj0028: Define conditions on level 1

- README.md
- rules/Proj2005.md
Documentation for new rule: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/217
> Proj2005: Escape XML nodes of resource values

- README.md
- general/nuget-packages.md
- rules/Proj0211.md
- rules/Proj0216.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/222
> Proj0216: Define the product name explicitly

- README.md
- rules/Proj0031.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/228
> Proj0031: Adopt preferred casing of nodes

- README.md
- rules/Proj4000.md
- rules/Proj4001.md
- rules/Proj4002.md
A prerequisite for parsing INI files.
> Proj4000: Invalid INI file

- README.md
- general/nuget-packages.md
- rules/Proj0243.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/242
> Proj0243: Generate software bill of materials

- README.md
- rules/Proj4050.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/246
> Proj4050: Header must be a GLOB

- README.md
- general/configuration.md
> Update configuration documentation

- README.md
- rules/Proj0032.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/issues/253
> Proj0032: Migrate away from BinaryFormatter

- README.md
- rules/Proj0033.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/issues/250
> Proj0033: Track uses of ""TODO"" tags

- general/sdk.md
Align with changes made in https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/267.
> Update SDK documentation

- README.md
- general/nuget-packages.md
- rules/Proj0244.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/issues/185
> Proj0244: Generate documentation file

- README.md
- rules/Proj0201.md
- rules/Proj0245.md
- rules/Proj0246.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/issues/139
> Proj0245 & Proj0246 VersionPrefix/Suffix Rules

- README.md
- rules/Proj0807.md
- rules/Proj0808.md
- rules/Proj0809.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/309
> Proj0808 and Proj0809 about <GlobalPackageReference>

- README.md
- navigation/general_project_rules.md
- navigation/licensing.md
- rules/Proj0500.md
- rules/Proj0501.md
Documentation for:
https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/315
https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/334
> Documentation for Proj0500 and Proj0501

- README.md
- navigation/licensing.md
- rules/Proj0500.md
- rules/Proj0501.md
- rules/Proj0502.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/340
> Proj0501: Package only contains a deprecated license URL

- README.md
- rules/Proj1103.md
- rules/Proj1104.md
Documentation required for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/351
> documentation for TUnit rule Proj1103 and Proj1104

- README.md
- rules/Proj0035.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/353
> Proj0035: Remove deprecated RestoreProjectStyle property

- README.md
- rules/Proj0810.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/354
> Proj0810: Remove unused package versions

- README.md
- rules/Proj0503.md
- rules/Proj0504.md
Documentation for PR https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/379
> Documentation for Proj0503 and Proj0504

- README.md
- rules/Proj0505.md
- rules/Proj0506.md
- rules/Proj0507.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/386
> Documentation for license registry validation

- rules/Proj0208.md
Closes https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/issues/388
> Proj0208: Add notion of getting release notes from file

- README.md
- rules/Proj0037.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/396
> Proj0037: Exclude compile when all assets are private

- README.md
- rules/Proj0038.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/408
> Proj0038: Specify NoWarn rule IDs fully

- README.md
- rules/Proj0400.md
- rules/Proj0401.md
> Proj0401: Only publish executables

- README.md
- rules/Proj0040.md
- rules/Proj0041.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/428
> Add documentation about NuGet security audits
