dotnet-project-file-analyzers/dotnet-project-file-analyzers.github.io

README.md, rules/Proj0021.md
`<ItemGroup>` build taks nodes such as `<Compile>`, `<Content>`, `<EmbeddedResource>`, `<None>`, and `<AdditionalFiles` should only have on task. Assigning multiple tasks to a single node seperated by semicolons (`;`) leads to longer lines
that are harder to read and maintain.
[Related PR](https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/110)
=> New Rule 0021: Build actions should have a single task

README.md, rules/Proj0022.md
Documentation for [PR 111](https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/111).
=> New Rule Proj0022: Build action includes should exist

README.md, rules/Proj1002.md, rules/Proj1003.md
[microsoft](https://microsoft.com) has implemented multiple generic Roslyn static code analysis rules both for C# and Visual Basic. These rules allow you to produce safe, reliable and maintainable code by helping you find and correct bugs, vulnerabilities and code smells in your codebase. It is strongly advised to enable this rules on all your projects.
See: [learn.microsoft.com/dotnet/fundamentals/code-analysis/overview](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/overview)
``` XML
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
<TargetFramework>net8.0</TargetFramework>
<EnableNETAnalyzers>true</EnableNETAnalyzers>
</PropertyGroup>
</Project>
```
=> New Rule 1002: Use Microsoft's analyzers

README.md, rules/Proj0023.md
The use of forward slashes (`/`) is preferred as they work both for UNIX and Windows. This is not true for backward slashes (`\`).
``` XML
<Project Sdk="Microsoft.NET.Sdk">
<Import Project="..\props\simple.props" />
<PropertyGroup>
<TargetFramework>net8.0</TargetFramework>
</PropertyGroup>
<ItemGroup>
<Compile Include="..\common\Code.cs" Link="Include\Code.cs" />
</ItemGroup>
<ItemGroup>
<None Remove="Files\*" />
</ItemGroup>
</Project>
```
``` XML
<Project Sdk="Microsoft.NET.Sdk">
<Import Project="../props/simple.props" />
<PropertyGroup>
<TargetFramework>net8.0</TargetFramework>
</PropertyGroup>
<ItemGroup>
<Compile Include="../common/Code.cs" Link="Include/Code.cs" />
</ItemGroup>
<ItemGroup>
<None Remove="Files/*" />
</ItemGroup>
</Project>
```
=> New Rule 0023: Use forward slashes

README.md, rules/Proj1101.md
When building code that goes into production, your code should not rely on a nightly build ore other pre-release version of an (external) package. This rule reports on packages that are not considered stable releases.
=> Proj1101: Package references should have stable versions

README.md, rules/Proj0804.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/153.
=> Proj0804: Use Version only with Central Package Management not enabled

README.md, rules/Proj0807.md
Documentation that goes with https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/156.
=> Proj0807: Use Directory.Packages.props only for Central Package Management

README.md, rules/Proj3000.md
Documentation for this [PR](https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/210).
=> Proj3000: Only use UTF-8 without BOM

README.md, rules/Proj0030.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/223.
=> Proj0030: Use VB.NET specific properties only in when applicable

README.md, rules/Proj0029.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/224
=> Proj0029: Use C# specific properties only when applicable

README.md, general/sdk.md
.NET Project File Analyzers ships with its own SDK. This allows files shared by multiple projects to be analyzed. It applies a *trick* also used by the [Microsoft.NET.Test.Sdk](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk); providing both a custom `.props` as a `.targets` MS Build file.
=> Documentation for the SDK

README.md, rules/Proj0700.md
Documentation for a rule linked to https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/230
=> Proj0700: Avoid defining <Compile> items in SDK project

README.md, rules/Proj0247.md, rules/Proj0248.md, rules/Proj0249.md, rules/Proj0250.md, rules/Proj0251.md, rules/Proj0252.md
Adds the following new rules:
* **Proj0247** Enable strict mode for package baseline validation
* **Proj0248** Enable strict mode for package runtime compatibility validation
* **Proj0249** Enable strict mode for package framework compatibility validation
* **Proj0250** Generate API compatibility suppression file
* **Proj0251** Enable API compatibility attribute checks
* **Proj0252** Enable API compatibility parameter name checks
Implementation: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/300
=> Add more rules for API compatibility validation

README.md, rules/Proj0034.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/331
=> Proj0034: Import statement could not be resolved

README.md, rules/Proj0502.md
As pointed out by @CptWesley, the most important indicator if a package is compliant, is the license of the package we're dealing with. So focus on getting that right first.
=> Rewrite the purpose of Proj0502

README.md, rules/Proj3002.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/372
=> Proj3002: Remove commented-out code

README.md, rules/Proj0036.md
Documentation for [issue 376](https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/issues/376). I'm not sure yet what title to give it. Any suggestions?
=> Proj0036: Remove None when redundant

rules/Proj0015.md, rules/Proj0016.md, rules/Proj0018.md, rules/Proj0019.md, rules/Proj2002.md
The rules about sorting now state that `StringComparison.OrdinalIgnoreCase` is applied.
Closes https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/issues/404
=> Add statement about how to sort

README.md, rules/Proj0039.md
I'm aware that this rule is opinionated, and I'm intending to release this with a severity info, instead of a warning. I'm also aware that this is by far the longest rule description, and is written more as a blog. Tips on how to improve that are (also) welcomed.
=> Proj0039: Treat all warnings as errors is considered a bad practice

README.md, rules/Proj0025.md
When converting the rulset fies we should advise to convert to `.globalconfig` over `.editorconfig`.
=> Advise the use of .globalconfig over .editorconfig

README.md, general/configuration.md, rules/Proj0017.md, rules/Proj0032.md, rules/Proj0042.md, rules/Proj0240.md, rules/Proj0241.md, rules/Proj0244.md, rules/Proj0247.md, rules/Proj0248.md, rules/Proj0249.md, rules/Proj0250.md, rules/Proj0251.md, rules/Proj0252.md, rules/Proj0501.md, rules/Proj0808.md, rules/Proj0809.md, rules/Proj2003.md, rules/Proj2004.md
Microsoft provides its documentation in multiple languages. By omitting the language ('/en-us/') it is up to the visitors preference which language Microsoft serves them, hence the changes.
=> Make MS URL's language agnostic

README.md, rules/Proj0218.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/467
=> Proj0218: Symbol package format snupkg requires debug type portable

README.md, rules/Proj0045.md
Documentation for https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/471
=> Proj0045: Convention-based MSBuild file names should use correct casing
